version: "3.9"

services:
  db:
    image: postgres:16
    container_name: murabaha_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: murabaha
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - kataloff-net

  backend:
    build: ./backend
    container_name: murabaha_backend
    depends_on:
      - db
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    networks:
      - kataloff-net
    restart: always

  frontend:
    build: ./frontend
    container_name: murabaha_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"      # <-- не конфликтует с Nginx
    networks:
      - kataloff-net
    restart: always

networks:
  kataloff-net:
    external: true

volumes:
  pgdata:


